### ISSUE TITLE
"packaging" not found

### ISSUE THREAD

**Issue by miranska** [DataCanvasIO/DeepTables#49]
Python package `packaging` is missing from the list of required packages in v.0.1.13. Here is the repro code:

```
>>> from deeptables.models.deepnets import WideDeep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./venv/lib/python3.7/site-packages/deeptables/models/__init__.py", line 6, in <module>
    from deeptables.models.deeptable import DeepTable
  File ".venv/lib/python3.7/site-packages/deeptables/models/deeptable.py", line 25, in <module>
    from ..utils.tf_version import tf_less_than
  File "./venv/lib/python3.7/site-packages/deeptables/utils/tf_version.py", line 7, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
```

Running `pip install packaging` fixes this.

**Comment by jackguagua** [comment]
@miranska Package `packaging` has been append into requirements.txt

**Comment by miranska** [comment]
Perfect, thank you!
