### ISSUE TITLE
DeepFM example: AttributeError: module 'sklearn.utils' has no attribute '_deprecate_positional_args'

### ISSUE THREAD

**Issue by unnir** [DataCanvasIO/DeepTables#73]
Hey,

got this error: 

`AttributeError: module 'sklearn.utils' has no attribute '_deprecate_positional_args'
`
I believe it is due to the new version of sckiti-learn.

**Comment by unnir** [comment]
thank you!

**Comment by yiming-lzx** [comment]
> Please downgrade scikit-learn to 0.24.x, eg:0.24.2. We'll fix this issue in next release.

it takes another problum,here is the error:

2022-07-05 09:21:04.474955: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-05 09:21:04.475023: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/root/cooka/dataset/iris_test_2/experiments/iris_test_2_1/train.py", line 32, in 
    from hypergbm.estimators import LightGBMEstimator, XGBoostEstimator, CatBoostEstimator
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypergbm/__init__.py", line 7, in 
    from .hyper_gbm import HyperGBM, HyperGBMEstimator, HyperGBMExplainer, HyperEstimator, HyperModel
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/hypergbm/hyper_gbm.py", line 13, in 
    import dask_ml.model_selection as dm_sel
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/dask_ml/__init__.py", line 4, in 
    from dask_ml.model_selection import _normalize
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/dask_ml/model_selection/__init__.py", line 6, in 
    from ._hyperband import HyperbandSearchCV
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/dask_ml/model_selection/_hyperband.py", line 12, in 
    from ._incremental import BaseIncrementalSearchCV
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/dask_ml/model_selection/_incremental.py", line 26, in 
    from sklearn.utils.metaestimators import available_if
ImportError: cannot import name 'available_if' from 'sklearn.utils.metaestimators' (/root/anaconda3/envs/py37/lib/python3.7/site-packages/sklearn/utils/metaestimators.py)
